# Generated by Django 4.2.3 on 2023-08-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='account_number',
            field=models.BigIntegerField(default=0),
        ),
    ]
